# Generated by Django 5.2.6 on 2025-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='home_address',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='preferred_payment_method',
            field=models.CharField(default='momo', max_length=10),
        ),
    ]
